### ISSUE TITLE
Implement NRIC functionality for patient details

### ISSUE THREAD

**Issue by yuntongzhang** [CS2103-AY1819S1-W14-3/main#21]
Our management system needs to allow enter NRIC of each patient. Currently, NRIC serves as the identifier for the patients.

**Subtasks:**
- [x] Allow add NRIC commands to be parsed.
- [x] Implement basic methods for the `NRIC` class.
- [x] Aggregate `NRIC` attribute to `Person` class, add relevant methods.
- [x] Adjust relevant tests for `NRIC` component.
