### ISSUE TITLE
Implement `addmeds` functionality

### ISSUE THREAD

**Issue by snajef** [CS2103-AY1819S1-W14-3/main#23]
Our patient manager needs to have functionality to add medication for patients.

### Subtasks
- [x] Add functionality for `addmeds` function
- [x] Add documentation for `addmeds` functionality in the User Guide
- [x] Add tests for the new `addmeds` functionality
