### ISSUE TITLE
Implement `viewmeds` functionality

### ISSUE THREAD

**Issue by snajef** [CS2103-AY1819S1-W14-3/main#26]
Users will need to be able to view the medications of a given patient.

### TODO
- [X] Add functionality to view patients' medication
- [ ] Add tests for `viewmeds` functionality
- [ ] Add new/update existing documentation for new functionality

**Comment by snajef** [comment]
PR was merged.
