### ISSUE TITLE
Implement sorting by column(s) for medication viewing

### ISSUE THREAD

**Issue by snajef** [CS2103-AY1819S1-W14-3/main#61]
Related to #51, #50, and #46

### TODO
- [X] Implement sorting by columns
- [X] Implement sorting by multiple columns
- [x] Update user guide
- [x] Update tests
